"""Removed admin_id in Comment table

Revision ID: 4370b31d156b
Revises: 08f3aaa6c68f
Create Date: 2024-05-28 15:53:43.237130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4370b31d156b'
down_revision = '08f3aaa6c68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_admin', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comment_admin', 'admin', ['admin_id'], ['id'])

    # ### end Alembic commands ###
