"""Test

Revision ID: 9e5ae3251fb5
Revises: 
Create Date: 2024-05-25 17:22:09.294106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5ae3251fb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_on', sa.Date(), nullable=True))
        batch_op.drop_column('pinned_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_date', sa.DATE(), nullable=True))
        batch_op.drop_column('cook_on')

    # ### end Alembic commands ###
