"""Removed admin_id in Recipe table

Revision ID: a9c886d677d0
Revises: 4370b31d156b
Create Date: 2024-05-30 13:49:04.481540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c886d677d0'
down_revision = '4370b31d156b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_admin', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_recipe_admin', 'admin', ['admin_id'], ['id'])

    # ### end Alembic commands ###
