"""Add approved column to Report model

Revision ID: de3bbb8ecd96
Revises: a9c886d677d0
Create Date: 2024-05-30 13:54:44.448146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3bbb8ecd96'
down_revision = 'a9c886d677d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
