"""Changed approved to reviewed

Revision ID: fd500e30e06a
Revises: 2aa78d0407a0
Create Date: 2024-05-30 21:30:55.448087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd500e30e06a'
down_revision = '2aa78d0407a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('reviewed')

    # ### end Alembic commands ###
